services:
  nginx:
    build:
      context: .
      dockerfile: nginx/dockerfile
    image: kreipikc/my-nginx-backtask:1.0.1
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    restart: unless-stopped
 